"use client";

import React from "react";
import Image from "next/image";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
  DialogDescription,
} from "@/components/ui/dialog"; // Auto-generated by shadcn
import { Button } from "@/components/ui/button"; // Auto-generated by shadcn

// Define the shape of the event prop
interface EventProps {
  title: string;
  desc: string;
  longDesc?: string; // Optional longer description for the modal
  posterUrl: string; // URL for the event poster
  registerLink: string; // Google Form link
}

interface EventRegisterModalProps {
  event: EventProps;
  children: React.ReactNode; // This will be the card that triggers the modal
}

export function EventRegisterModal({
  event,
  children,
}: EventRegisterModalProps) {
  return (
    <Dialog>
      <DialogTrigger asChild>{children}</DialogTrigger>
      <DialogContent className="bg-neutral-900 border-green-800 text-white max-w-md">
        <DialogHeader>
          <DialogTitle className="text-2xl text-green-300">
            {event.title}
          </DialogTitle>
          <DialogDescription className="text-neutral-400">
            {event.desc}
          </DialogDescription>
        </DialogHeader>
        <div className="mt-4 space-y-4">
          <div className="w-full aspect-[16/9] rounded-md overflow-hidden relative">
            <Image
              src={event.posterUrl}
              alt={`${event.title} Poster`}
              layout="fill"
              objectFit="cover"
            />
          </div>
          {event.longDesc && (
            <p className="text-sm text-neutral-300">{event.longDesc}</p>
          )}
          <Button
            asChild
            className="w-full bg-gradient-to-r from-green-500 to-green-400 text-black font-semibold text-lg py-6 hover:brightness-110 animate-neon-glow"
          >
            <a
              href={event.registerLink}
              target="_blank"
              rel="noopener noreferrer"
            >
              Register for this Event
            </a>
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}
